name: Build Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'lib/**'
      - 'example/android/**'
      - 'example/lib/**'
      - 'pubspec.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libvulkan-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Decode Keystore File
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > example/android/app/key.jks

      - name: Create key.properties
        run: |
          echo "storeFile=key.jks" > example/android/key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> example/android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> example/android/key.properties
          echo "releasePassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> example/android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> example/android/key.properties
          echo "releaseAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> example/android/key.properties
    
      - name: CD into example
        run: cd example

      - name: Setup Flutter
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk -v --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: example-android-apk
          path: example/build/app/outputs/apk/release

      - name: Build appbundle
        run: |
          flutter build appbundle

      - name: Rename AAB
        run: mv example/build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/example-android-bundle.aab

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: example-android-aab
          path: example/build/app/outputs/bundle/release/example-android-bundle.aab